[template]
src = "traefik.toml.tmpl"
dest = "/etc/traefik.toml"
prefix = "/latest"
keys = [
    "/self",
    "/containers",
    "/services",
]
[template]
src = "certificates.sh.tmpl"
dest = "/usr/local/bin/certificates.sh"
prefix = "/latest"
keys = [
    "/self",
    "/containers",
    "/services",
]
